// Mocks generated by Mockito 5.0.16 from annotations
// in tech_challenge_flutter/test/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tech_challenge_flutter/data/github_repo/dao/api_rest_repo_dao.dart'
    as _i7;
import 'package:tech_challenge_flutter/data/github_repo/model/api_response_model.dart'
    as _i3;
import 'package:tech_challenge_flutter/domain/github_repo/repo_model.dart'
    as _i6;
import 'package:tech_challenge_flutter/domain/github_repo/repo_repository.dart'
    as _i4;
import 'package:tech_challenge_flutter/domain/utils.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePair_0<E, F> extends _i1.Fake implements _i2.Pair<E, F> {}

class _FakeApiResponseModel_1 extends _i1.Fake implements _i3.ApiResponseModel {
}

/// A class which mocks [RepoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepoRepository extends _i1.Mock implements _i4.RepoRepository {
  MockRepoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Pair<List<_i6.RepoModel>, int>>
      getRepositoriesWithNumberOfPages(
              {String? remoName,
              _i2.SortType? sortType = _i2.SortType.created,
              _i2.SortDirection? sortDirection = _i2.SortDirection.asc,
              int? limit = 10,
              int? page = 1}) =>
          (super.noSuchMethod(
                  Invocation.method(#getRepositoriesWithNumberOfPages, [], {
                    #remoName: remoName,
                    #sortType: sortType,
                    #sortDirection: sortDirection,
                    #limit: limit,
                    #page: page
                  }),
                  returnValue: Future<_i2.Pair<List<_i6.RepoModel>, int>>.value(
                      _FakePair_0<List<_i6.RepoModel>, int>()))
              as _i5.Future<_i2.Pair<List<_i6.RepoModel>, int>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ApiRestRepoDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiRestRepoDao extends _i1.Mock implements _i7.ApiRestRepoDao {
  MockApiRestRepoDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.ApiResponseModel> getRepos(
          {String? repoName,
          String? sortType,
          String? sortDirection,
          int? limit,
          int? page}) =>
      (super.noSuchMethod(
              Invocation.method(#getRepos, [], {
                #repoName: repoName,
                #sortType: sortType,
                #sortDirection: sortDirection,
                #limit: limit,
                #page: page
              }),
              returnValue:
                  Future<_i3.ApiResponseModel>.value(_FakeApiResponseModel_1()))
          as _i5.Future<_i3.ApiResponseModel>);
  @override
  String toString() => super.toString();
}
