// Mocks generated by Mockito 5.0.16 from annotations
// in tech_challenge_flutter/test/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tech_challenge_flutter/domain/github_repo/repo_model.dart'
    as _i5;
import 'package:tech_challenge_flutter/domain/github_repo/repo_repository.dart'
    as _i3;
import 'package:tech_challenge_flutter/domain/utils.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePair_0<E, F> extends _i1.Fake implements _i2.Pair<E, F> {}

/// A class which mocks [RepoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepoRepository extends _i1.Mock implements _i3.RepoRepository {
  MockRepoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Pair<List<_i5.RepoModel>, int>>
      getRepositoriesWithNumberOfPages(
              {String? remoName,
              _i2.SortType? sortType = _i2.SortType.created,
              _i2.SortDirection? sortDirection = _i2.SortDirection.asc,
              int? limit = 10,
              int? page = 1}) =>
          (super.noSuchMethod(
                  Invocation.method(#getRepositoriesWithNumberOfPages, [], {
                    #remoName: remoName,
                    #sortType: sortType,
                    #sortDirection: sortDirection,
                    #limit: limit,
                    #page: page
                  }),
                  returnValue: Future<_i2.Pair<List<_i5.RepoModel>, int>>.value(
                      _FakePair_0<List<_i5.RepoModel>, int>()))
              as _i4.Future<_i2.Pair<List<_i5.RepoModel>, int>>);
  @override
  String toString() => super.toString();
}
