include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_positional_boolean_parameters: false
    avoid_classes_with_only_static_members: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.config.dart"
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    parameter_assignments: error
    # https://github.com/rrousselGit/freezed/issues/527
    invalid_annotation_target: ignore